repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # versión estable actual
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        files: \.(c|h|md|yaml|yml)$
      - id: trailing-whitespace
        files: \.(c|h|md|yaml|yml)$
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.6
    hooks:
      - id: clang-format
        name: Formating C files with Clang-Format
        files: \.(c|cpp|h)$
